/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GamersPlay;

import java.io.File;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import config.Config;
import funciones.ComponentResizer;
import funciones.funciones;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import uk.co.caprica.vlcj.binding.LibVlc;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;
import uk.co.caprica.vlcj.player.MediaPlayer;
import uk.co.caprica.vlcj.player.MediaPlayerEventAdapter;
import uk.co.caprica.vlcj.runtime.RuntimeUtil;

public class GamersPlay extends javax.swing.JFrame {

    private EmbeddedMediaPlayerComponent player = new EmbeddedMediaPlayerComponent();
    private File file;
    
    static
    {
        NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), "C:\\Program Files (x86)\\GamersStore");
        Native.loadLibrary(RuntimeUtil.getLibVlcLibraryName(), LibVlc.class);
    }
    
    private int vol = 100;
    private boolean AccionProgres = true;
    private int x=0;
    private boolean reproduciendo = false;
    private long duracion = 0;
    private int tamJs = 200;
    
    public GamersPlay()
    {
        initComponents();
        
        Config.setIcon(this);
        Config.center(this);
        
        Config.setControlBar(this, jP_bar, jL_minimizar, jL_maximizar, jL_cerrar);
        jP_bar.setVisible(false);
        
        jL_loading = new JLabel(new ImageIcon(getClass().getResource("/lib/images/gif-loading-black-250x250.gif")));
        jL_loading.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        jPanel8.add(jL_loading);
        
        jP_video.add(player);
        
        player.getMediaPlayer().addMediaPlayerEventListener
        (
            new MediaPlayerEventAdapter()
            {
                public void positionChanged(MediaPlayer mp, float posicion)
                {
                    if(AccionProgres)
                    {
                        if(jPanel8.isVisible())
                        {
                           jPanel8.setVisible(false);
                        }
                        
                        int value =  Math.round(posicion * tamJs);
                        jS_progreso.setValue(value);
                        
                        int transcurridoSeg = Math.round((posicion * duracion) / 1000);
                        jL_transcurrido.setText(funciones.convertirSeg(transcurridoSeg));
                    }
                }
                public void finished(MediaPlayer mediaPlayer)
                {
                    jS_progreso.setValue(tamJs);
                }
                public void lengthChanged(MediaPlayer mediaPlayer,long newLength)
                {
                    //System.out.println(newLength);
                }
                public void mediaDurationChanged(MediaPlayer mediaPlayer, long newDuration)
                {
                    int duracionSeg = Math.round(newDuration / 1000);
                    jL_duracion.setText(funciones.convertirSeg(duracionSeg));
                    duracion = newDuration;
                    
                    tamJs = duracionSeg;
                    jS_progreso.setMaximum(tamJs);
                    
                    reproduciendo = true;
                }
                public void timeChanged(MediaPlayer mediaPlayer, long newTime)
                {
                    //System.out.println(newTime);
                }
                
                
            }
        );
        
       
        
    }
    
    public void play(String url, String titulo)
    {
        if(url.length() != 0)
        {
            player.getMediaPlayer().playMedia(url);    
            //player.getMediaPlayer().playMedia("C:\\Users\\Luis Acxis\\Downloads\\video.mp4");    
            player.getMediaPlayer().setVolume(vol);           
            this.setTitle("GamersPlay: "+titulo);
            player.getMediaPlayer().setBrightness(2f);
            jL_play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/images/icon-pause-white-32x32.png")));            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jP_bar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jL_title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jL_minimizar = new javax.swing.JLabel();
        jL_maximizar = new javax.swing.JLabel();
        jL_cerrar = new javax.swing.JLabel();
        jP_video = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jL_loading = new javax.swing.JLabel();
        jP_control = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jS_progreso = new javax.swing.JSlider();
        jPanel5 = new javax.swing.JPanel();
        jL_play = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jL_vol = new javax.swing.JLabel();
        jS_volumen = new javax.swing.JSlider();
        jPanel7 = new javax.swing.JPanel();
        jL_duracion = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jL_transcurrido = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GamersPlay");
        setMinimumSize(new java.awt.Dimension(550, 300));
        setPreferredSize(new java.awt.Dimension(720, 500));

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(750, 510));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jP_bar.setBackground(new java.awt.Color(0, 51, 204));
        jP_bar.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jP_bar.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jL_title.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_title, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jL_title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jP_bar.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jL_minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/images/icon-minimizar-gray-32x32.png"))); // NOI18N
        jL_minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jL_minimizar);

        jL_maximizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_maximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/images/icon-minimizar-gray-32x32.png"))); // NOI18N
        jL_maximizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jL_maximizar);

        jL_cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/images/icon-close-gray-32x32.png"))); // NOI18N
        jL_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jL_cerrar);

        jP_bar.add(jPanel1, java.awt.BorderLayout.EAST);

        jPanel4.add(jP_bar, java.awt.BorderLayout.NORTH);

        jP_video.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jP_video.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        jPanel8.setLayout(new java.awt.BorderLayout());
        jPanel8.add(jL_loading, java.awt.BorderLayout.CENTER);

        jP_video.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel4.add(jP_video, java.awt.BorderLayout.CENTER);

        jP_control.setBackground(new java.awt.Color(0, 0, 0));
        jP_control.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jS_progreso.setBackground(new java.awt.Color(255, 255, 255));
        jS_progreso.setMinimum(1);
        jS_progreso.setValue(0);
        jS_progreso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jS_progresoStateChanged(evt);
            }
        });
        jS_progreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jS_progresoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jS_progresoMouseReleased(evt);
            }
        });
        jPanel3.add(jS_progreso);

        jP_control.add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_play.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/images/icon-play-white-32x32.png"))); // NOI18N
        jL_play.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jL_play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_playMouseClicked(evt);
            }
        });
        jL_play.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jL_playKeyPressed(evt);
            }
        });
        jPanel5.add(jL_play, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jP_control.add(jPanel5, java.awt.BorderLayout.WEST);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_vol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_vol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/images/icon-volumenAlto-white-32x32.png"))); // NOI18N
        jL_vol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.add(jL_vol, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jS_volumen.setBackground(new java.awt.Color(255, 255, 255));
        jS_volumen.setValue(100);
        jS_volumen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jS_volumenStateChanged(evt);
            }
        });
        jPanel6.add(jS_volumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 220, 20));

        jP_control.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_duracion.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jL_duracion.setForeground(new java.awt.Color(255, 255, 255));
        jL_duracion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel7.add(jL_duracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 60, 20));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/images/icon-fullscreen-white32x32.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 40, 40));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("/");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 20, 20));

        jL_transcurrido.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jL_transcurrido.setForeground(new java.awt.Color(255, 255, 255));
        jL_transcurrido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel7.add(jL_transcurrido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 70, 20));

        jP_control.add(jPanel7, java.awt.BorderLayout.EAST);

        jPanel4.add(jP_control, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jL_playKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jL_playKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jL_playKeyPressed

    private void jL_playMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_playMouseClicked
        if(!reproduciendo)
        {   
            jL_play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/images/icon-pause-white-32x32.png")));
            player.getMediaPlayer().play();
            reproduciendo = true;
        }
        else
        {
            jL_play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/images/icon-play-white-32x32.png")));
            player.getMediaPlayer().setPause( player.getMediaPlayer().isPlaying()?true:false );
            reproduciendo = false;
        }
    }//GEN-LAST:event_jL_playMouseClicked

    private void jS_progresoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jS_progresoMousePressed
        AccionProgres = false;
    }//GEN-LAST:event_jS_progresoMousePressed

    private void jS_progresoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jS_progresoMouseReleased
        AccionProgres = true;
    }//GEN-LAST:event_jS_progresoMouseReleased

    private void jS_volumenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jS_volumenStateChanged
        vol = jS_volumen.getValue();
        player.getMediaPlayer().setVolume(vol);
        
        if(vol == 0)
        {
            jL_vol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/images/icon-mute-white-32x32.png")));
        }
        else if(vol >= 1 && vol <= 30)
        {
            jL_vol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/images/icon-volumenBajo-white-32x32.png")));
        }
        else if(vol >= 31 && vol <= 60)
        {
            jL_vol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/images/icon-volumenMedio-white-32x32.png")));
        }
        else if(vol >= 61)
        {
            jL_vol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/images/icon-volumenAlto-white-32x32.png")));
        }
    }//GEN-LAST:event_jS_volumenStateChanged

    private void jS_progresoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jS_progresoStateChanged
        if(!AccionProgres)
        {
            float posicion = jS_progreso.getValue()/(float)tamJs; 
            player.getMediaPlayer().setPosition(posicion);
        }
        float posicion = jS_progreso.getValue()/(float)tamJs;
        int transcurridoSeg = Math.round((posicion * duracion) / 1000)-1;
        jL_transcurrido.setText(funciones.convertirSeg(transcurridoSeg));
    }//GEN-LAST:event_jS_progresoStateChanged
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamersPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamersPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamersPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamersPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamersPlay().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_cerrar;
    private javax.swing.JLabel jL_duracion;
    private javax.swing.JLabel jL_loading;
    private javax.swing.JLabel jL_maximizar;
    private javax.swing.JLabel jL_minimizar;
    private javax.swing.JLabel jL_play;
    private javax.swing.JLabel jL_title;
    private javax.swing.JLabel jL_transcurrido;
    private javax.swing.JLabel jL_vol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jP_bar;
    private javax.swing.JPanel jP_control;
    private javax.swing.JPanel jP_video;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSlider jS_progreso;
    private javax.swing.JSlider jS_volumen;
    // End of variables declaration//GEN-END:variables
}
